http://localhost:3000/

###

http://localhost:3000/login/devicecode

###

http://localhost:3000/login/devicecode/zzz

###

http://localhost:3000/login/oauth

###

# oauth callback URL
http://localhost:3000/
